version: "3.8"

services:
  server:
    container_name: trivia-server
    restart: always
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - database
    entrypoint: ["/bin/bash", "./entrypoint.sh"]

  client:
    container_name: trivia-client
    restart: always
    build: ./client
    ports:
      - "80:3000"
    links:
      - "server:client"

  database:
    container_name: trivia-database
    image: mysql
    restart: always
    ports:
      - "3305:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=K#assaf14
      - MYSQL_DATABASE=trivia
